
package service.se.kth.webservice.project.parsing;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SyntacticComparatorService", targetNamespace = "http://parsing.project.webservice.kth.se/", wsdlLocation = "http://130.229.165.53:9091/comparator?wsdl")
public class SyntacticComparatorService
    extends Service
{

    private final static URL SYNTACTICCOMPARATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SYNTACTICCOMPARATORSERVICE_EXCEPTION;
    private final static QName SYNTACTICCOMPARATORSERVICE_QNAME = new QName("http://parsing.project.webservice.kth.se/", "SyntacticComparatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://130.229.165.53:9091/comparator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SYNTACTICCOMPARATORSERVICE_WSDL_LOCATION = url;
        SYNTACTICCOMPARATORSERVICE_EXCEPTION = e;
    }

    public SyntacticComparatorService() {
        super(__getWsdlLocation(), SYNTACTICCOMPARATORSERVICE_QNAME);
    }

    public SyntacticComparatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYNTACTICCOMPARATORSERVICE_QNAME, features);
    }

    public SyntacticComparatorService(URL wsdlLocation) {
        super(wsdlLocation, SYNTACTICCOMPARATORSERVICE_QNAME);
    }

    public SyntacticComparatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYNTACTICCOMPARATORSERVICE_QNAME, features);
    }

    public SyntacticComparatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SyntacticComparatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SyntacticComparator
     */
    @WebEndpoint(name = "SyntacticComparatorPort")
    public SyntacticComparator getSyntacticComparatorPort() {
        return super.getPort(new QName("http://parsing.project.webservice.kth.se/", "SyntacticComparatorPort"), SyntacticComparator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SyntacticComparator
     */
    @WebEndpoint(name = "SyntacticComparatorPort")
    public SyntacticComparator getSyntacticComparatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://parsing.project.webservice.kth.se/", "SyntacticComparatorPort"), SyntacticComparator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYNTACTICCOMPARATORSERVICE_EXCEPTION!= null) {
            throw SYNTACTICCOMPARATORSERVICE_EXCEPTION;
        }
        return SYNTACTICCOMPARATORSERVICE_WSDL_LOCATION;
    }

}
