
package service.se.kth.webservice.project.parsing;

import se.kth.webservice.project.parsing.XmlModelMapping;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SyntacticComparator", targetNamespace = "http://parsing.project.webservice.kth.se/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SyntacticComparator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateSimmilarityRating", targetNamespace = "http://parsing.project.webservice.kth.se/", className = "se.kth.webservice.project.parsing.CalculateSimmilarityRating")
    @ResponseWrapper(localName = "calculateSimmilarityRatingResponse", targetNamespace = "http://parsing.project.webservice.kth.se/", className = "se.kth.webservice.project.parsing.CalculateSimmilarityRatingResponse")
    @Action(input = "http://parsing.project.webservice.kth.se/SyntacticComparator/calculateSimmilarityRatingRequest", output = "http://parsing.project.webservice.kth.se/SyntacticComparator/calculateSimmilarityRatingResponse")
    public float calculateSimmilarityRating(
        @WebParam(name = "arg0", targetNamespace = "")
        XmlModelMapping arg0,
        @WebParam(name = "arg1", targetNamespace = "")
                XmlModelMapping arg1);

}
