ALTER TABLE adjpositions ADD CONSTRAINT pk_adjpositions PRIMARY KEY (synsetid,wordid);
ALTER TABLE adjpositiontypes ADD CONSTRAINT pk_adjpositiontypes PRIMARY KEY (position);
ALTER TABLE casedwords ADD CONSTRAINT pk_casedwords PRIMARY KEY (casedwordid);
ALTER TABLE lexdomains ADD CONSTRAINT pk_lexdomains PRIMARY KEY (lexdomainid);
ALTER TABLE lexlinks ADD CONSTRAINT pk_lexlinks PRIMARY KEY (word1id,synset1id,word2id,synset2id,linkid);
ALTER TABLE linktypes ADD CONSTRAINT pk_linktypes PRIMARY KEY (linkid);
ALTER TABLE morphs ADD CONSTRAINT pk_morphs PRIMARY KEY (morphid);
ALTER TABLE morphmaps ADD CONSTRAINT pk_morphmaps PRIMARY KEY (morphid,pos,wordid);
ALTER TABLE postypes ADD CONSTRAINT pk_postypes PRIMARY KEY (pos);
ALTER TABLE samples ADD CONSTRAINT pk_samples PRIMARY KEY (synsetid,sampleid);
ALTER TABLE semlinks ADD CONSTRAINT pk_semlinks PRIMARY KEY (synset1id,synset2id,linkid);
ALTER TABLE senses ADD CONSTRAINT pk_senses PRIMARY KEY (wordid,synsetid);
ALTER TABLE synsets ADD CONSTRAINT pk_synsets PRIMARY KEY (synsetid);
ALTER TABLE vframes ADD CONSTRAINT pk_vframes PRIMARY KEY (frameid);
ALTER TABLE vframemaps ADD CONSTRAINT pk_vframemaps PRIMARY KEY (synsetid,wordid,frameid);
ALTER TABLE vframesentences ADD CONSTRAINT pk_vframesentences PRIMARY KEY (sentenceid);
ALTER TABLE vframesentencemaps ADD CONSTRAINT pk_vframesentencemaps PRIMARY KEY (synsetid,wordid,sentenceid);
ALTER TABLE words ADD CONSTRAINT pk_words PRIMARY KEY (wordid);
ALTER TABLE casedwords ADD CONSTRAINT unq_casedwords_cased UNIQUE KEY (cased);
ALTER TABLE morphs ADD CONSTRAINT unq_morphs_morph UNIQUE KEY (morph);
ALTER TABLE senses ADD CONSTRAINT unq_senses_senseid UNIQUE KEY (senseid);
ALTER TABLE senses ADD CONSTRAINT unq_senses_sensekey UNIQUE KEY (sensekey);
ALTER TABLE words ADD CONSTRAINT unq_words_lemma UNIQUE KEY (lemma);
ALTER TABLE adjpositions ADD INDEX k_adjpositions_synsetid (synsetid);
ALTER TABLE adjpositions ADD INDEX k_adjpositions_wordid (wordid);
ALTER TABLE casedwords ADD INDEX k_casedwords_wordid (wordid);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_linkid (linkid);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_synset1id (synset1id);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_synset1id_word1id (synset1id,word1id);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_synset2id (synset2id);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_synset2id_word2id (synset2id,word2id);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_word1id (word1id);
ALTER TABLE lexlinks ADD INDEX k_lexlinks_word2id (word2id);
ALTER TABLE morphmaps ADD INDEX k_morphmaps_morphid (morphid);
ALTER TABLE morphmaps ADD INDEX k_morphmaps_wordid (wordid);
ALTER TABLE samples ADD INDEX k_samples_synsetid (synsetid);
ALTER TABLE semlinks ADD INDEX k_semlinks_linkid (linkid);
ALTER TABLE semlinks ADD INDEX k_semlinks_synset1id (synset1id);
ALTER TABLE semlinks ADD INDEX k_semlinks_synset2id (synset2id);
ALTER TABLE senses ADD INDEX k_senses_lexid (lexid);
ALTER TABLE senses ADD INDEX k_senses_synsetid (synsetid);
ALTER TABLE senses ADD INDEX k_senses_wordid (wordid);
ALTER TABLE synsets ADD INDEX k_synsets_lexdomainid (lexdomainid);
ALTER TABLE vframemaps ADD INDEX k_vframemaps_frameid (frameid);
ALTER TABLE vframemaps ADD INDEX k_vframemaps_synsetid (synsetid);
ALTER TABLE vframemaps ADD INDEX k_vframemaps_wordid (wordid);
ALTER TABLE vframesentencemaps ADD INDEX k_vframesentencemaps_sentenceid (sentenceid);
ALTER TABLE vframesentencemaps ADD INDEX k_vframesentencemaps_synsetid (synsetid);
ALTER TABLE vframesentencemaps ADD INDEX k_vframesentencemaps_wordid (wordid);
ALTER TABLE adjpositions ADD CONSTRAINT fk_adjpositions_synsetid FOREIGN KEY k_adjpositions_synsetid (synsetid) REFERENCES synsets (synsetid);
ALTER TABLE adjpositions ADD CONSTRAINT fk_adjpositions_wordid FOREIGN KEY k_adjpositions_wordid (wordid) REFERENCES words (wordid);
ALTER TABLE casedwords ADD CONSTRAINT fk_casedwords_wordid FOREIGN KEY k_casedwords_wordid (wordid) REFERENCES words (wordid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_linkid FOREIGN KEY k_lexlinks_linkid (linkid) REFERENCES linktypes (linkid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_synset1id FOREIGN KEY k_lexlinks_synset1id (synset1id) REFERENCES synsets (synsetid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_synset2id FOREIGN KEY k_lexlinks_synset2id (synset2id) REFERENCES synsets (synsetid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_word1id FOREIGN KEY k_lexlinks_word1id (word1id) REFERENCES words (wordid);
ALTER TABLE lexlinks ADD CONSTRAINT fk_lexlinks_word2id FOREIGN KEY k_lexlinks_word2id (word2id) REFERENCES words (wordid);
ALTER TABLE morphmaps ADD CONSTRAINT fk_morphmaps_morphid FOREIGN KEY k_morphmaps_morphid (morphid) REFERENCES morphs (morphid);
ALTER TABLE morphmaps ADD CONSTRAINT fk_morphmaps_wordid FOREIGN KEY k_morphmaps_wordid (wordid) REFERENCES words (wordid);
ALTER TABLE samples ADD CONSTRAINT fk_samples_synsetid FOREIGN KEY k_samples_synsetid (synsetid) REFERENCES synsets (synsetid);
ALTER TABLE semlinks ADD CONSTRAINT fk_semlinks_linkid FOREIGN KEY k_semlinks_linkid (linkid) REFERENCES linktypes (linkid);
ALTER TABLE semlinks ADD CONSTRAINT fk_semlinks_synset1id FOREIGN KEY k_semlinks_synset1id (synset1id) REFERENCES synsets (synsetid);
ALTER TABLE semlinks ADD CONSTRAINT fk_semlinks_synset2id FOREIGN KEY k_semlinks_synset2id (synset2id) REFERENCES synsets (synsetid);
ALTER TABLE senses ADD CONSTRAINT fk_senses_synsetid FOREIGN KEY k_senses_synsetid (synsetid) REFERENCES synsets (synsetid);
ALTER TABLE senses ADD CONSTRAINT fk_senses_wordid FOREIGN KEY k_senses_wordid (wordid) REFERENCES words (wordid);
ALTER TABLE synsets ADD CONSTRAINT fk_synsets_lexdomainid FOREIGN KEY k_synsets_lexdomainid (lexdomainid) REFERENCES lexdomains (lexdomainid);
ALTER TABLE vframemaps ADD CONSTRAINT fk_vframemaps_frameid FOREIGN KEY k_vframemaps_frameid (frameid) REFERENCES vframes (frameid);
ALTER TABLE vframemaps ADD CONSTRAINT fk_vframemaps_synsetid FOREIGN KEY k_vframemaps_synsetid (synsetid) REFERENCES synsets (synsetid);
ALTER TABLE vframemaps ADD CONSTRAINT fk_vframemaps_wordid FOREIGN KEY k_vframemaps_wordid (wordid) REFERENCES words (wordid);
ALTER TABLE vframesentencemaps ADD CONSTRAINT fk_vframesentencemaps_sentenceid FOREIGN KEY k_vframesentencemaps_sentenceid (sentenceid) REFERENCES vframesentences (sentenceid);
ALTER TABLE vframesentencemaps ADD CONSTRAINT fk_vframesentencemaps_synsetid FOREIGN KEY k_vframesentencemaps_synsetid (synsetid) REFERENCES synsets (synsetid);
ALTER TABLE vframesentencemaps ADD CONSTRAINT fk_vframesentencemaps_wordid FOREIGN KEY k_vframesentencemaps_wordid (wordid) REFERENCES words (wordid);
