//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 11:28:42 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kth.se/ict/id2208/Matching", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package se.kth.webservice.project.output_model;
